name = "TimerOutputComparisons"
uuid = "59c811e7-adb4-4b01-a05e-50a2dd0b99a2"
version = "1.0.0"
authors = ["John Omotani <john.omotani@ukaea.uk> and contributors"]

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
GLMakie = "0.13.10"
JLD = "0.13.5"
TimerOutputs = "0.5.29"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
